config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'places#index'
	resources :places do
		resources :comments, only: :create
		resources :photos, only: :create
	end
	resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :place
	validates :message, presence: true, length: { maximum: 140, minimum: 5 }
 	validates :rating, presence: true

 	after_create :send_comment_email

	RATINGS = {
		'one star': '1_star',
		'two stars': '2_stars',
		'three stars': '3_stars',
		'four stars': '4_stars',
		'five stars': '5_stars'
	}

	def humanized_rating
		RATINGS.invert[self.rating]
	end

	def send_comment_email
		NotificationMailer.comment_added(self).deliver_now
	end 

end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :picture, PictureUploader

	validates :caption, presence: true, length: { maximum: 140, minimum: 5 }
 	validates :picture, presence: true
	
	belongs_to :place
	
end

app/models/place.rb
class Place < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :photos, dependent: :destroy
	
	geocoded_by :address
	after_validation :geocode

	validates :name, length: {minimum: 4}
	validates :address, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :places
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@place = Place.find(params[:place_id])
		@place.comments.create(comment_params.merge(user: current_user))
		redirect_to place_path(@place)
	end

	private

	def comment_params
		params.require(:comment).permit(:message, :rating)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def create
		@place = Place.find(params[:place_id])
		@place.photos.create(photo_params)
		redirect_to place_path(@place)
	end

	private

	def photo_params
		params.require(:photo).permit(:picture, :caption)
	end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
	
	def index
		@places = Place.all.paginate(page: params[:page], per_page: 5).order("created_at DESC")
	end

	def new
		@place = Place.new
	end

	def create
		@place = current_user.places.create(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@place = Place.find(params[:id])
		@comment = Comment.new
		@photo = Photo.new
	end

	def edit
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render plain: 'Not Allowed! Please sign in!', status: :forbidden
		end
	end

	def update
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render plain: 'Not Allowed! Please sign in!', status: :forbidden
		end

		@place.update_attributes(place_params)
		if @place.valid?
			redirect_to root_path
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@place = Place.find(params[:id])
		if @place.user != current_user
			return render plain: 'Not Allowed! Please sign in!'
		end

		@place.destroy
		redirect_to root_path
	end

	private

	def place_params
		params.require(:place).permit(:name, :address, :description)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <meta name="viewport" content="width=device-width, initial-scale=0.75, maximum-scale=0.90">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to 'My Profile', user_path(current_user), class: 'nav-link' %>
          </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
      <span class="navbar-item">
         <%= link_to new_place_path, class: 'nav-link' do %> 
            <i class="fa fa-plus-circle"></i>
            New Place
            <% end %>
      </span>
    </div>
  </nav>

   <% if notice.present? %>
    <p class="alert alert-info"><%= notice%></p>
    <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert%></p>
    <% end %>
 
  <%= yield %>
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
	<h1>Edit Your Place</h1>
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :description %>
		<br />
		<%= f.submit 'Update', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/places/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag 'slider1.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption">
      	<h3>You can find great restaurants in Toronto.</h3>
      </div>
    </div>
    <div class="carousel-item">
       <%= image_tag 'slider2.jpg', class: 'd-block img-fluid' %>
    	<div class="carousel-caption">
       		<h3><font color="#99ff33">Share your key finds here - along with photos!</font></h3>
   		</div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'slider3.jpg', class: 'd-block img-fluid' %>
      <div class="carousel-caption">
       		<h3><font color="#41d9f4">Post comments, and let others comment too!</font></h3>
   		</div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br />

<div>
<% @places.each do |place| %>
	<div class="booyah-box col-10 offset-1">
		<% if place.photos.present? %>
			<div class="float-right">
				<%= image_tag place.photos.last.picture.url, :size => "350x200" %>
				<br /><br />
			</div>
		<% end %>
		<h1><%= link_to place.name, place_path(place) %></h1><br />
		<i><%= place.address %></i><br /><br />
		<p><%= place.description %></p><br />

		<small><%= place.user.email %><br />
		<%= link_to 'View User Profile', user_path(place.user) %></small>
		<br />
		
		<% if place.comments.present? %>
			<div class="col-12">
				<blockquote>
					<% if place.comments.last.humanized_rating.present? %>
						<b><%= place.comments.last.humanized_rating %></b>: 
					<% end %>
					<%= place.comments.last.message %>
					<small><%= place.comments.last.user.email %>
					&nbsp;[<%= link_to 'View User Profile', user_path(place.comments.last.user) %>]</small>
				</blockquote>
			</div>
		<% end %>
	</div>
<% end %>
</div>

<br />

<div class="digg_pagination offset-1">
<%= will_paginate @places %>
</div>

<br />

<div class="footer-box col-10 offset-1">
	<small><i>
	This app was proudly developed by Raj Mukerjee. His email is: raj_muk@hotmail.com
	</i></small>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
	<h1>Enter Your Place Details</h1>
	<%= simple_form_for @place do |f| %>
		<%= f.input :name %>
		<%= f.input :address %>
		<%= f.input :description %>
		<br />
		<%= f.submit 'Create', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/places/show.html.erb
<div class ="booyah-box col-10 offset-1">
	<h1><%= @place.name %></h1>
	<br /><br />
	<i><%= @place.address %></i>
	<br />
	<br />
	<p><%= @place.description %></p>
	<br /><small>
	Place added by: <b><font color="green"><%= @place.user.email %></font></b>&nbsp;
	[<%= link_to 'View User Profile', user_path(@place.user) %>]</small>

<% if @place.latitude.present? && @place.longitude.present? %>
		<script>
	      function initMap() {
	        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

	        var map = new google.maps.Map(document.getElementById('map'), {
	          zoom: 14,
	          center: myLatLng
	        });

	        var marker = new google.maps.Marker({
	          position: myLatLng,
	          map: map,
	          title: 'Hello World!'
	        });
	      }
	    </script>
	    <script async defer
	    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyATXquIWJj8L5jgrd9Cm2LYiOtP0hs4xrM&callback=initMap">
	    </script>

  	<div id="map"></div>

 <% end %>

 <br />
	<div class = "float-right">
		<h3 class="float-left">
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#exampleModal2">
			  Add A Photo
			</button>
		<% if current_user && current_user == @place.user %>
		<%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
		<%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'}, class: 'btn btn-danger' %>&nbsp;
		<% end %>
	</div>
	<br />
	<br />
</div>

<!-- Modal 1 for Comments -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><b>Add A Comment</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    	<%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
	      <div class="modal-body">
	      		<small><i>[NOTE: You must select a rating AND post 5-140 characters for your comment to be saved.]</i></small><br /><br />
				<%= f.input :message %>
				<%= f.input :rating, as: :select, collection: Comment::RATINGS %>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			<%= f.submit "Add a Comment", class: 'btn btn-primary' %>
	      </div>
	    <% end %>
    </div>
  </div>
</div>

<br />

<div class="col-10 offset-1">
	<h3 class="float-left"><u>Comments:</u></h3>
	<!-- Button trigger modal -->
	<button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#exampleModal">
	  Add A Comment
	</button>
</div>

<br />
<br />
<br />

<div class="clear"></div>

<div class="row">
	<% @place.comments.each do |comment| %>
		<div class="col-12 col-sm-6">
			<blockquote>
				<% if comment.humanized_rating.present? %>
					<b><%= comment.humanized_rating %></b>: 
				<% end %>
				<%= comment.message %>
				<small><%= comment.user.email %>
				<%= link_to '[View User Profile]', user_path(comment.user) %></small></blockquote>
			</blockquote>
		</div>
	<% end %>
</div>

<!-- Modal 2 for Photos -->
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel2"><b>Add A Photo</b></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    	<%= simple_form_for @photo, url: place_photos_path(@place) do |x| %>
	      <div class="modal-body">
	      		<small><i>[NOTE: You must add a caption (5-140 characters) AND upload a photo for this to be saved.]</i></small><br /><br />
				<%= x.input :picture %>
				<%= x.input :caption %>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			<%= x.submit "Add a Photo", class: 'btn btn-primary' %>
	      </div>
	    <% end %>
    </div>
  </div>
</div>

<% if @place.photos.present? %>
	<div class="booyah-box col-10 offset-1">
		<h3><u>Uploaded Photos:</u></h3>
		<br />
		<div class="middle">
		<% @place.photos.each do |photo| %>
	  	<%= image_tag photo.picture.url, :size => "350x200" %>
	  	<br />
	    <small><%= photo.caption %></small>
	    <br />
	    <br />
	    <% end %>
		</div>
	</div>
<% end %>

app/views/users/show.html.erb
<div class="booyah-box col-10 offset-1">
	<div class="row">
		<div class="col-sm-2">
			<%= image_tag 'user.png' %>
		</div>
		<div class="clear"></div>
		<div class="col-8">
			<h1><small><b><font color="#51c934"><%= @user.email %></font></small></b></h1>
			<h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
			<br />
			<h4>- <%= @user.comments.count %> total comments</h4>
			<h4>- <%= @user.comments.where(rating: '5_stars').count %> five-star review(s) in total</h4>
		</div>
	</div>
</div>

<% if @user.comments.present? %>
	<br />
	<h2 class="text-center"><u>My Comments</u></h2>
	<br />
	<div class="row">
	<% @user.comments.each do |comment| %>
		<div class="col-12 col-sm-6">
			<h3 class="text-center"><i><%= link_to comment.place.name, place_path(comment.place) %></i></h3>
			<blockquote>
				<% if comment.humanized_rating.present? %>
					<b><%= comment.humanized_rating %></b>: 
				<% end %>
				<%= comment.message %>
				</small>
			</blockquote>
		</div>
	<% end %>
	</div>
<% end %>

<div class="clear"></div>

<% if @user.places.present? %>
	<br />
	<h2 class="text-center"><u>My Places</u></h2>
	<br />
	<% @user.places.each do |place| %>
		<div class="booyah-box col-10 offset-1">
			<h1><%= link_to place.name, place_path(place) %></h1><br />
			<i><%= place.address %></i><br /><br />
			<p><%= place.description %></p>

			<% if place.comments.present? %>
	      	<div class="col-12">
	        	<blockquote>
	          		<% if place.comments.last.humanized_rating.present? %>
	            	<b><%= place.comments.last.humanized_rating %></b> -
	          		<% end %>
	          		<%= place.comments.last.message %>
	          		<small><%= place.comments.last.user.email %>&nbsp;
	          		[<%= link_to 'View User Profile', user_path(place.comments.last.user) %>]</small>
	          		</small>
	        	</blockquote>
	      	</div>
	    	<% end %>
		</div>
	<% end %>
<% end %>